#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="argonaut"
prepare_service

check_service_initialized init 20-php-fpm

if var_true "${ENABLE_ARGONAUT}" ;  then
    print_notice "Enabling Argonaut Server"
else
    service_stop 30-argonaut
fi

liftoff
