#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="fusiondirectory"

prepare_service 10-nginx
prepare_service
#check_service_initialized init 30-argonaut

fusiondirectory_configure_application
fusiondirectory_configure_orchestrator
fusiondirectory_configure_themes
fusiondirectory_configure_plugins
fusiondirectory_configure_webroot
fusiondirectory_configure_ldap_client
fusiondirectory_configure_overrides

liftoff
